# ids of every component of visualisation, used for callbacks
X_AXIS_DROPDOWN = "x-asis-dropdown"
Y_AXIS_DROPDOWN = "y-asis-dropdown"
FILTER = "filter"
SEARCH_BAR = "search-bar"
SCATTER_PLOT = "scatter-plot"
POINT_COMPARISON = "point-comparison"
# LAYERS = "layers-dropdown"
PCA = "pca"
CATEGORY_DROPDOWN_1 = "cat-1"
CATEGORY_DROPDOWN_2 = "cat-2"
CATEGORY_DROPDOWN_3 = "cat-3"
CATEGORY_DROPDOWN_4 = "cat-4"
